import { z } from "zod";

import { prisma } from "@/lib/prisma";
import { ProjectError } from "@/lib/projects";
import {
  REQUIREMENT_CATEGORIES,
  REQUIREMENT_PRIORITIES,
} from "@/lib/requirements";

export const CLARIFICATION_STATUSES = ["pending", "answered", "converted"] as const;
export type ClarificationStatus = (typeof CLARIFICATION_STATUSES)[number];

/**
 * Zod schema for a single clarification item generated by the AI
 */
export const clarificationItemSchema = z.object({
  ambiguity: z
    .string()
    .trim()
    .min(1, "Ambiguity description is required")
    .describe("The specific ambiguity, assumption, or gap identified in the project or requirement"),
  requirementId: z
    .string()
    .optional()
    .nullable()
    .describe("ID of the related requirement if this is refining an existing requirement, or null"),
  question: z
    .string()
    .trim()
    .min(1, "Question is required")
    .describe("The clear, focused clarifying question asked to the user"),
  options: z
    .array(z.string().trim().min(1))
    .min(2, "At least 2 suggested options are required")
    .max(5, "At most 5 suggested options are permitted")
    .describe("2 to 5 concrete choices or suggested answers for the user to pick or customize"),
  category: z
    .enum(REQUIREMENT_CATEGORIES)
    .default("Functional")
    .describe("The architectural category this clarification pertains to"),
});

export type ClarificationItem = z.infer<typeof clarificationItemSchema>;

/**
 * Zod schema for the clarification agent's overall output
 */
export const clarificationResponseSchema = z.object({
  summary: z
    .string()
    .trim()
    .min(1, "Summary is required")
    .describe("Brief 1-2 sentence overview of the analysis and identified ambiguities"),
  clarifications: z
    .array(clarificationItemSchema)
    .min(1, "At least one clarification question must be generated")
    .describe("List of clarifying questions to resolve ambiguities"),
});

export type ClarificationResponse = z.infer<typeof clarificationResponseSchema>;

/**
 * Zod schema for submitting an inline answer
 */
export const answerClarificationSchema = z.object({
  answer: z
    .string({ message: "Answer is required" })
    .trim()
    .min(1, "Answer cannot be empty")
    .max(3000, "Answer cannot exceed 3000 characters"),
});

export type AnswerClarificationInput = z.infer<typeof answerClarificationSchema>;

/**
 * Zod schema for converting a clarification into a requirement or constraint
 */
export const convertClarificationSchema = z.object({
  target: z.enum(["requirement", "constraint"]).default("requirement"),
  title: z
    .string()
    .trim()
    .max(200)
    .optional(),
  category: z.enum(REQUIREMENT_CATEGORIES).optional(),
  priority: z.enum(REQUIREMENT_PRIORITIES).default("Medium"),
});

export type ConvertClarificationInput = z.infer<typeof convertClarificationSchema>;

/**
 * Verifies that a clarification exists and its parent project belongs to the authenticated user.
 */
export async function getAuthorizedClarification(
  clarificationId: string,
  userId: string,
) {
  if (!clarificationId || typeof clarificationId !== "string") {
    throw new ProjectError("Invalid clarification ID", 400);
  }

  const clarification = await prisma.clarification.findUnique({
    where: { id: clarificationId },
    include: {
      project: {
        select: {
          id: true,
          userId: true,
          name: true,
          constraints: true,
        },
      },
    },
  });

  if (!clarification) {
    throw new ProjectError("Clarification not found", 404);
  }

  if (clarification.project.userId !== userId) {
    throw new ProjectError(
      "Forbidden: You do not have permission to access this clarification",
      403,
    );
  }

  return clarification;
}
